### ISSUE TITLE
Support presign HTTP POST 

### ISSUE THREAD

**Issue by recunius** [ar90n/serverless-s3-local#17]
Is there any desire to support a presigned HTTP Post?

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#createPresignedPost-property
https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-post-example.html

I believe it's the only way to limit the size of an upload from a browser securely, so unfortunately I don't want to use putObject or ManagedUpload.

**Comment by ar90n** [comment]
Hi @recunius 
Thanks for your comment.
presigned HTTP post is interesting technology.
But I think that supporting it is out of scope of this project.
serverless-s3-local uses [s3rver](https://github.com/jamhall/s3rver) as its backend.
So please comment to [s3rver's issues](https://github.com/jamhall/s3rver/issues).

**Comment by n1ru4l** [comment]
There is already an issue for this: https://github.com/jamhall/s3rver/issues/153
If you have any thoughts @recunius feel free to share them there 😊

**Comment by ar90n** [comment]
@n1ru4l 
Thanks for your comment.
It sounds good !
So I will close this issue.
