### ISSUE TITLE
Serverless 3.0.0 deprecation warning: option type requirement

### ISSUE THREAD

**Issue by bebbi** [ar90n/serverless-s3-local#198]
The following warning is triggered:

```
Deprecation warning: CLI options definitions were upgraded with "type" property
(which could be one of "string", "boolean", "multiple").

Below listed plugins do not predefine type for introduced options:
             - ServerlessS3Local for "port", "directory", "buckets", "cors", "noStart", "allowMismatchedSignatures", "website", "serviceEndpoint", "httpsProtocol", "vhostBuckets"
```

Fix: Every option should simply be given a `type` of value `string`, `boolean`, `multiple`:
https://www.serverless.com/framework/docs/providers/aws/guide/plugins#defining-options

**Comment by ar90n** [comment]
Hi @bebbi 

Sorry for my late reply. Thanks for your good advice! 
I fixed these issues by the way you told me.
These issues are solved in v0.6.15. 
Thanks!!
