### ISSUE TITLE
s3rver require cors config to be xml

### ISSUE THREAD

**Issue by mbudm** [ar90n/serverless-s3-local#20]
It looks like just setting ```cors:true``` for s3rver options is no longer supported. Perhaps update the cors config to be a path to a local policy? Then do something like:

```
const corsPolicy = cors ?
        fs.readFileSync(path.resolve(process.cwd(), cors), 'utf8') :
        false ;

this.client = new S3rver({
        port,
        hostname: host,
        silent: false,
        directory,
        cors: corsPolicy,
```

**Comment by ar90n** [comment]
@mbudm 
Sorry for my late reply and thanks for your great comment.
What you said is exactly true.
I fixed it as follow.

```
       fs.ensureDirSync(dirPath); // Create destination directory if not exist
       const directory = fs.realpathSync(dirPath);

+      const corsPolicy = cors ?
+            fs.readFileSync(path.resolve(this.serverless.config.servicePath, cors) , 'utf8') :
+            cors ;
+
       this.client = new S3rver({
         port,
         hostname: host,
         silent: false,
         directory,
-        cors,
+        cors: corsPolicy,
       }).run((err, s3Host, s3Port) => {
         if (err) {
           console.error('Error occurred while starting S3 local.');
```

In this case, cors in serverless.yml may have three values.
The first is the relative path to cors policy xml file from serverless.yml.
The second is false.
The third is undefined.
In the third case, s3rver enables cors and use default cors policy.

**Comment by mbudm** [comment]
Late reply? 4 days later, that's pretty efficient if you ask me.

Fixed.
