### ISSUE TITLE
version 0.3.6 has broken environment variables for serverless-offline

### ISSUE THREAD

**Issue by gevorggalstyan** [ar90n/serverless-s3-local#29]
For some reason, the plugin is launching all the functions, and at that moment the serverless environment variables are not populated yet. 

With enough sophisticated factories, you get errors on missing environment variables that the functions need to work.

This is a very critical bug! 
I suppose this may be related to lines 145-154 in index.js

**Comment by ar90n** [comment]
@gevorggalstyan 
Thanks for your reports.
I'm sorry for this enbug.
I'm starting to investigate what happened.
Please use v0.3.5 until I solve this issue.

**Comment by ar90n** [comment]
@gevorggalstyan 
I'm sorry.
I couldn't figure out what you said in the previous comment correctly.
Because my English is poor.

In my recognition, I thought that you said that environment variables was missing  on running functions.
But environment variables was set correctly in my local testing.

If you don't mind, please share your code which has this issue ?

**Comment by gevorggalstyan** [comment]
@ar90n 
You got it correctly :)

Yes, the environment variables are missing. Our project is very big to demo the bug. But I will create a smaller one and will provide you with details on how to reproduce the bug shortly.

P.S. Thank you for responsiveness.

**Comment by gevorggalstyan** [comment]
@ar90n 

Please find attached the sample service I have created.

You should be able to start it with `sls offline start`, but first, visit `handler.js` file and take a look at line 3. It is simply printing out the custom environment variable (CUSTOM_VARIABLE) that I have placed there.

As soon as you run the serverless offline you will notice that it is printing `undefined` in your terminal. It is the console.log line from handler.js file. If you visit http://localhost:3000/ you will see that it prints `THIS_IS_THE_VALUE` as it already has the environment variables loaded.

If you downgrade to version 0.3.5 you will not see the `undefined` after the first run, as that version was working as expected and not running all the functions on launch. That has been introduced in version 0.3.6 and I am failing to see a good reason for that.

Please LMK if I can help you with more info.

[my-service.zip](https://github.com/ar90n/serverless-s3-local/files/2118955/my-service.zip)

**Comment by ar90n** [comment]
Hi @gevorggalstyan 
Thanks for your explicit description and good example.
I think I solved this issue at v0.3.8.
Please try it !!

**Comment by gevorggalstyan** [comment]
Indeed! You have it fixed. I really appreciate the quick turnaround.
