### ISSUE TITLE
Uploaded files path

### ISSUE THREAD

**Issue by dfloresgonz** [ar90n/serverless-s3-local#32]
Where are the files I upload stored? What is the /tmp directory for? I have a tmp folder in my project but files are not uploaded there.

**Comment by mbharanya** [comment]
`/tmp` is the full path of the location where the local S3 data is saved. You can choose any place you want.
If you're on Linux or MacOS `/tmp` already exists and is in the `/` directory, not your project directory

https://en.wikipedia.org/wiki/Unix_filesystem#Conventional_directory_layout

**Comment by dfloresgonz** [comment]
Oh great I did not see it, in windows is in the C:/ directory, thanks a lot.

**Comment by ar90n** [comment]
HI @dfloresgonz .
Sorry for my late reply. Please use aws s3 client to get files like the following.
```
$ aws --endpoint http://localhost:8000 s3api get-object --bucket local-bucket --key 1234 ./1234
```

@mbharanya 
Thanks for your great support.

**Comment by dfloresgonz** [comment]
Thank you
