### ISSUE TITLE
Create Bucket silently fails if you do not have a local .aws/configuration file

### ISSUE THREAD

**Issue by nschirmer** [ar90n/serverless-s3-local#34]
AWS-SDK requires an accessKeyId/secretAccessKey be used when performing S3 bucket operations. Most devs likely use the aws cli and have therefore run `aws configure` at some point to generate a local configuration file.

Not everyone has done this though, and a serverless-offline project should not have an outside dependency like this.

If the configuration file doesn't exist, and you don't pass these two values through as options when initializing the S3 client, bucket creation within this plugin will silently fail.

To address this, I've opened a PR that adds these two properties to the options and uses them in the `getClient` method: https://github.com/ar90n/serverless-s3-local/pull/33

**Comment by ar90n** [comment]
Closed because #33 is merged.
