### ISSUE TITLE
@aws-sdk/client-s3 returns an error with PutObjectCommand

### ISSUE THREAD

**Issue by LC-09** [ar90n/serverless-s3-local#492]
What I'm trying to do it's to save a file csv with a fake s3 (with serverless-s3-local plugin), but for some reason, the endpoint is giving an error. I followed these instructions [serverless-s3-local][1] but with library "@aws-sdk/client-s3".

Note: I run the command described in the documentation `aws --endpoint http://localhost:4569 s3 cp ~/tmp/data.csv s3://local-bucket/userdata.csv --profile s3local` and everything works well. So maybe the problem could be in the params or methods that I'm using, but I haven't could find the solution.

This is the following error that I'm getting:

    Error: getaddrinfo ENOTFOUND local-bucket.localhost
        at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
        at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17) {   errno: -3008,   code: 'ENOTFOUND',   syscall: 'getaddrinfo',   hostname: 'local-bucket.localhost',   '$metadata': { attempts: 1, totalRetryDelay: 0 } }

These are some configurations that I have in the custom and resources sections in serverless.yml

    custom:
      # S3
      s3:
        bucketName: local-bucket
        host: localhost
        directory: /tmp

    resources:
      Resources:
        NewResource:
          Type: AWS::S3::Bucket
          Properties:
            BucketName: ${self:custom.s3.bucketName}

And this is my temporal code:

      main.ts
      import { S3Manager } from "../../../../shared/utils/aws/s3Manager";

      private _contentTypeXlsx: string = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
      private _contentTypeCsv: string = 'text/csv;charset=utf-8';

      const s3Config= new S3Manager('S3RVER', 'S3RVER', 'us-east-1', 'local-bucket');
      let bucketKey
      let responseUpload
      const fileName = `ExportedFile.csv`;
      bucketKey = `ExportedFiles/${Date.now()}/${fileName}`;
      const fileCsv = await new ObjectsToCsv(arrivals);
      responseUpload = await s3Manager.uploadFiles({  Key: bucketKey, Body: fileCsv.toString(), ContentType: this._contentTypeCsv });
----
    s3Config.ts

    import { S3Client, PutObjectCommand, GetObjectCommand } from "@aws-sdk/client-s3";
    export class S3Manager {
        
            s3Client: any;
            awsS3: any
            bucketParams: any;
        
            constructor(keyId: string, accessKey: string, region: string, bucketName: string) {
                const configAwsClient = {
                    s3ForcePathStyle: true,
                    accessKeyId: keyId,
                    secretAccessKey: accessKey,
                    endpoint: 'http://localhost:4569',
                };
                this.s3Client = new S3Client(configAwsClient);
                this.bucketParams = {
                    Bucket: bucketName
                }
            }
        
            async uploadFiles(filters: {}): Promise<any> {
                let success = true;
                try {
                    var params = {
                        ...this.bucketParams,
                        ...filters
                    };
                    const command = await new PutObjectCommand(params);
                    const response = await this.s3Client.send(command);
                    console.info('Response of putObject', response);
                }
                catch (err) {
                    success = false;
                    console.log(err);
                }
                return success;
            } }

  [1]: https://www.serverless.com/plugins/serverless-s3-local

**Comment by ar90n** [comment]
Hi @LC-09 

Thanks for your comment. And I'm sorry for this trouble.
It seems wrong to specify credentials. Please try the following codes.

```js
            const configAwsClient = {
                s3ForcePathStyle: true,
                credentials: {
                    accessKeyId: keyId,
                    secretAccessKey: accessKey,
                },
                endpoint: 'http://localhost:4569',
            };
```

**Comment by LC-09** [comment]
I've tried with these changes, but it's showing the same error yet.

            const configAwsClient = {
                s3ForcePathStyle: true,
                credentials: {
                    accessKeyId: keyId,
                    secretAccessKey: accessKey,
                },
                endpoint: 'http://localhost:4569',
            };

**Comment by LC-09** [comment]
> Hi @LC-09
> 
> Thanks for your comment. And I'm sorry for this trouble. It seems wrong to specify credentials. Please try the following codes.
> 
> ```js
>             const configAwsClient = {
>                 s3ForcePathStyle: true,
>                 credentials: {
>                     accessKeyId: keyId,
>                     secretAccessKey: accessKey,
>                 },
>                 endpoint: 'http://localhost:4569',
>             };
> ```

I've tried with these changes, but it's showing the same error yet.

```
Error: getaddrinfo ENOTFOUND local-bucket.localhost
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'local-bucket.localhost',
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
Error: getaddrinfo ENOTFOUND local-bucket.localhost
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'local-bucket.localhost',
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
```

**Comment by LC-09** [comment]
Nice! It already works without erros with these configurations:

            const configAwsClient = {
                forcePathStyle: true,
                credentials: {
                    accessKeyId: keyId,
                    secretAccessKey: accessKey,
                },
                endpoint: 'http://localhost:4569',
            };

I can see now the objects saved locally.
Thank you @ar90n!
