### ISSUE TITLE
Support for get object attributes (Checksum)

### ISSUE THREAD

**Issue by colesiegel** [ar90n/serverless-s3-local#571]
Hi,

Is there any support for setting and retrieving object attributes such as `Checksum`? 

I would like to be able to `PUT` a file in the local bucket with `x-amz-checksum-sha256` and then retrieve this value using `GetObjectAttributes`: https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetObjectAttributes.html

Example:

```
aws s3api get-object-attributes --bucket bucket --key document/file.png --object-attributes Checksum
{
    "LastModified": "2022-07-11T17:02:38+00:00",
    "VersionId": "n.WUv1jVIYRx_mvziPTSHjSY0VyVplEH",
    "Checksum": {
        "ChecksumSHA256": "vxcz2rPw/8iKGWYsZc0TlsP4kYCVqq13s4pHUEKz94E="
    }
}
```

When I `PUT` file in local bucket with `x-amz-checksum-sha256`, it doesn't seem to set anything in the `metadata.json` file. I am not sure where I should write this info to if I want to be able to read it using `GetObjectAttributes`.

Any suggestions? Thanks!

PS - seen this issue (https://github.com/ar90n/serverless-s3-local/issues/89 ) but not sure if checksum is actually part of the object metadata, or stored elsewhere? It is not under the metadata fields in the AWS console

![image](https://user-images.githubusercontent.com/14875904/179297760-83cb0ab1-8c9b-4bca-9cee-227c8196f879.png)

**Comment by ar90n** [comment]
Hi @colesiegel 
serverless-s3-local only launches S3rver. So if S3rver supports this feature, serverless-s3-local will be able to meet your requirement. Please try S3rver independently and check if it supports this feature?

**Comment by colesiegel** [comment]
Thanks @ar90n I raised a feature request there, seems like it's not supported yet. 

https://github.com/jamhall/s3rver/issues/801
