### ISSUE TITLE
s3.getObjectTagging method not implemented?

### ISSUE THREAD

**Issue by whobutsb** [ar90n/serverless-s3-local#67]
Hello! I'm trying to upload an object with --tagging parameter set and then trying to retrieve the the object tags using the s3.getObjectTagging method. I keep receiving the following error:

```
 message: 'A parameter you provided implies functionality that is not implemented',
  code: 'NotImplemented',
  region: null,
  time: 2019-06-17T16:57:47.151Z,
  requestId: null,
  extendedRequestId: undefined,
  cfId: undefined,
  statusCode: 501,
  retryable: true }
```

Here is my upload command: 
`AWS_ACCESS_KEY_ID=S3RVER AWS_SECRET_ACCESS_KEY=S3RVER aws --endpoint http://localhost:8000 s3api put-object --bucket local-bucket --key 'test.mp3' --body ./test/test.mp3 --tagging 'TagSet=[{Key=MESSAGE_ID,Value=1540}]'`

Here is my handler for the s3 code: 
```
module.exports.s3EventResponse = (event, context, callback) => {
  const key = event.Records[0].s3.object.key;
  const bucket_params = {
    Bucket: 'local-bucket',
    Key: key
  };
  s3.getObjectTagging(bucket_params, function(err, data) {
    if(err){
      console.error(err);
      return callback(null, 'error');
    }
    console.log(data);
    callback(null, 'ok');
  });
  // console.log(JSON.stringify(event));
};
```

I'm going to assume that this method has not been implemented into `serverless-s3-local`? Or am I missing something in my code.  Thank you for the assistance!

**Comment by ar90n** [comment]
Hi @whobutsb 
Thanks for your report. As you said, serverless-s3-local doesn't support s3 tagging. I'm sorry to bother you.

**Comment by whobutsb** [comment]
No worries!  Just wanted to make sure I wasn't missing something.  Thank you for the reply.
