### ISSUE TITLE
Objects Posted with PreSignedPOST urls do not trigger events

### ISSUE THREAD

**Issue by randonia** [ar90n/serverless-s3-local#76]
Relevant packages and versions: 
```    "s3rver": "^3.5.0",
    "serverless-offline": "^5.10.1",
    "serverless-s3-local": "^0.5.0",
```

I managed to get [Presigned URLs](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#createPresignedPost-property) working with `serverless-s3-local` by manually installing `s3rver@3.5.0`. The problem is now my events no longer trigger off of simple requests.

Example configuration to reproduce:

Handler configuration
```yaml
...
    events:
      - s3:
          bucket: my-bucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .mp4
          existing: true
```

Example code
```JavaScript
const AWS = require('aws-sdk');
const fs = require('fs');
const request = require('request-promise-native');

const S3 = new AWS.S3({
  accessKeyId: 'S3RVER',
  endpoint: new AWS.Endpoint('http://localhost:9393'),
  s3ForcePathStyle: true,
  secretAccessKey: 'S3RVER',
});

function uploadFile() {
  console.log('Uploading file...');
  const genParams = {
    Bucket: 'my-bucket',
    Expires: 3600,
    Fields: {
      key: 'uploads/test/source.mp4',
      'Content-Type': 'video/mp4',
    },
  };
  S3.createPresignedPost(genParams, (err, result) => {
    if (err) {
      console.error('Failed to make, err=', err);
      return;
    }
    console.log('Pre-signed result:', result);
    // Upload the file
    const formData = {
      ...result.fields,
      file: fs.createReadStream('/path/to/video.mp4'),
    };

    const opts = {
      formData,
      uri: result.url,
      method: 'POST',
    };
    request(opts)
      .then((res) => console.log('Upload result:', res))
      .catch((err1) => console.error(err1));
  });
}

uploadFile();
```

As a sanity check, the following `aws-cli` command functions as expected, triggering my S3 event:

```shell
aws s3 cp --profile s3local --endpoint http://localhost:9393 /path/to/video.mp4 s3://my-bucket/uploads/test/source.mp4
```

Is there something I am able to do to continue complete local development or is this something that's not easily fixed/corrected with this module?

Thanks, let me know if there's any information I'm missing or forgot to provide, or if this issue really belongs in `s3rver`'s issues list.

**Comment by randonia** [comment]
Upon further investigation, I've realized this is an issue better suited for s3rver. I discovered that the [`postObject`](https://github.com/jamhall/s3rver/blob/master/lib/controllers/object.js#L267) method specifically doesn't trigger an event, so I will recreate my issue there.

**Comment by ar90n** [comment]
@randonia 
Thank for your comment! if your request has been merged into s3rver, I will make serverless-s3-local  use it.

**Comment by randonia** [comment]
Thanks @ar90n - I've got it in a PR on the main repo. Judging by their release cadence we should expect it sometime in the next week or three.
