### ISSUE TITLE
Add support for "allow-mismatched-signatures" s3rver config

### ISSUE THREAD

**Issue by hakimio** [ar90n/serverless-s3-local#79]
@ar90n 
It would be nice if you could add support for "allow-mismatched-signatures" s3rver option.

**Comment by ar90n** [comment]
@hakimio 
Thanks for your comment. In v0.5.2, allowMismatchedSignatures option is supported. Please try it!

**Comment by hakimio** [comment]
@ar90n 
The new option seems to be working well.
