### ISSUE TITLE
https support

### ISSUE THREAD

**Issue by sublimator** [ar90n/serverless-s3-local#9]
It would be handy if this had https support :) 

Would it make sense to move the backend to https://github.com/scality/S3?

Would you accept a pull request for such?

**Comment by ar90n** [comment]
Hi @sublimator 

Thanks for your suggestion.
Your idea is great and I agree with you.
Of course, if you send me a PR, I will accept it !

**Comment by sublimator** [comment]
Ok, if I find the time :)

I was recently informed about ‘localstack’ by atlassian so will evaluate
that before undertaking the task.

Have you any experience yourself with localstack?

**Comment by ar90n** [comment]
I know localstack too but I have not used it.
I think localstack is the best solution for production grade large scale project.
By the way, I think serverless-s3-local is suited for tiny project such as a couple of apis and S3.

If you are going to develop large system, I recommend you use localstack !
Of course, your PR is welcome anytime :)

**Comment by sublimator** [comment]
Yeah, I would rather rely on simple things I know not to try and do
anything too fancy with than something that tries but fails to actually
replicate production environment. I'm a bit skeptical about localstack to
be honest. AWS should contribute to it or something like it really!

**Comment by sublimator** [comment]
I had a little play with scality s3, and it's a bit more complicated, requiring messing with configuration of https, and even secret keys, and working around self signed https issues in the aws-sdk.

e.g. 

```typescript
function specialAgentAllow()
{
  const agent = new https.Agent({
    // changed to false, different from the default one
    rejectUnauthorized: false //
  });

  // delegate maxSockets to globalAgent
  Object.defineProperty(agent, 'maxSockets', {
    enumerable: true,
    get: function() { return https.globalAgent.maxSockets; }
  });

  return agent;
}

// TODO: s3 offline plugin doesn't work with https://
const params = process.env.IS_OFFLINE? {
  endpoint: 'https://localhost:' + process.env.LOCAL_S3_PORT,
  httpOptions: {agent: specialAgentAllow()},
  s3ForcePathStyle: true
```

Currently I just patched my node_modules/ version of your plugin to use similar self signed cert work arounds, and using `noStart` option ... 

Hrmmm ...
